django_assets/assets/urls.py
from django.conf.urls import url
from django.urls import path

from django_assets.assets import views

app_name = 'assets'

urlpatterns = [

    url(
        r'^$',
        views.HomeView.as_view(),
        name="home"
    ),

    path('asset', views.AssetListView.as_view(), name='asset-list'),
    path('location', views.LocationListView.as_view(), name='location-list'),
    path('supplier', views.SupplierListView.as_view(), name='supplier-list'),

]

django_assets/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

admin.site.site_header = 'Assets Administration'

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^jet/', include('jet.urls', 'jet')),
    url(r'^jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),
    url(r'^', include('django_assets.assets.urls', namespace='assets')),
    path('accounts/', include('django.contrib.auth.urls')),
] + static(settings.STATIC_URL, document_root=settings.MEDIA_ROOT)

django_assets/assets/models/asset.py
# -*- coding: utf-8 -*-
from enum import Enum

from django.db import models
from django.utils.translation import ugettext_lazy as _

from .location import Location
from .category import Category
from .owner import Owner
from .supplier import Supplier


class AssetStates(Enum):
    REPA = _('En réparation')
    INUSE = _("En cours d'utilisation")
    HS = _('Hors Service')
    DFCT = _('Défectueux')
    OK = _('Fonctionnel')


class Asset(models.Model):
    name = models.CharField(verbose_name=_("Name"), max_length=200)

    value = models.DecimalField(max_digits=19, decimal_places=2)
    acquisition_date = models.DateField()

    state = models.CharField(
        verbose_name=_("State"),
        max_length=5,
        choices=[(state.name, state.value) for state in AssetStates],
        default='OK',
    )

    location = models.ForeignKey(Location, on_delete=models.SET_NULL, null=True)
    category = models.ManyToManyField(Category, blank=True)
    supplier = models.ForeignKey(Supplier, on_delete=models.SET_NULL, null=True)
    owner = models.ForeignKey(Owner, on_delete=models.SET_NULL, null=True)

    # Creation and last modifications dates
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

django_assets/assets/models/category.py
from django.db import models
from django.utils.translation import ugettext_lazy as _


class Category(models.Model):
    name = models.CharField(verbose_name=_("Name"), max_length=200)

    # Creation and last modifications dates
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name_plural = "Categories"

    def __str__(self):
        return self.name

django_assets/assets/models/location.py
from django.db import models
from django.utils.translation import ugettext_lazy as _


class Location(models.Model):
    name = models.CharField(verbose_name=_("Name"), max_length=200)

    # Creation and last modifications dates
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

django_assets/assets/models/owner.py
from django.db import models
from django.utils.translation import ugettext_lazy as _


class Owner(models.Model):
    name = models.CharField(verbose_name=_("Name"), max_length=200)

    # Creation and last modifications dates
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

django_assets/assets/models/supplier.py
from django.db import models
from django.utils.translation import ugettext_lazy as _


class Supplier(models.Model):
    name = models.CharField(verbose_name=_("Name"), max_length=200)
    contact = models.CharField(verbose_name=_("Contact"), max_length=200)
    account_id = models.CharField(verbose_name=_("Account ID"), max_length=200)

    # Creation and last modifications dates
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

django_assets/assets/forms/asset.py
from django import forms

from .models import Asset


class AssetForm(forms.ModelForm):
    class Meta:
        model = Asset
        exclude = []

django_assets/assets/views.py
from django.views.generic import TemplateView
from django.views.generic.list import ListView
from django.contrib.auth.models import User
from django.contrib.auth.mixins import LoginRequiredMixin

from .models import Asset
from .models import Location
from .models import Supplier


class HomeView(LoginRequiredMixin, TemplateView):
    template_name = "home.html"
    extra_context = {
        'users': User.objects.all()
    }


class AssetListView(LoginRequiredMixin, ListView):
    model = Asset
    template_name = 'generic_list.html'


class LocationListView(LoginRequiredMixin, ListView):
    model = Location
    template_name = 'generic_list.html'


class SupplierListView(LoginRequiredMixin, ListView):
    model = Supplier
    template_name = 'generic_list.html'

django_assets/assets/templates/generic_list.html
{% extends 'base.html' %}
{% load assets %}

{% block content %}
{% get_meta model=view.model as class %}
<section class="statistic">
    <div class="section__content ">
        <div class="container-fluid">
            <div class="row">
              <div class="col-md-12">
                  <!-- USER DATA-->
                  <div class="user-data">
                      <h3 class="title-3 m-b-30">
                          {{ class.name }}{{ object_list|length|pluralize }}
                      </h3>
                      <div class="table-responsive table-data">
                          <table class="table">
                              <thead>
                                  <tr>
                                    {% for field in class.fields %}
                                    <td>{{ field.verbose_name|title }}</td>
                                    {% endfor %}
                                  </tr>
                              </thead>
                              <tbody>
                                {% for object in object_list %}
                                  <tr>
                                    {% for field in class.fields %}
                                    <td>{{ object|getfield:field }}</td>
                                    {% endfor %}
                                  </tr>
                                {% empty %}
                                  <tr>
                                    <td colspan="{{ class.fields|length }}" class="text-center bg-warning">No {{ class.name }}</td>
                                  </tr>
                                {% endfor %}
                              </tbody>
                          </table>
                      </div>
                  </div>
              </div>
            </div>
          </div>
        </div>
      </section>
{% endblock %}

django_assets/assets/templates/home.html
{% extends 'base.html' %}
{% load i18n assets %}

{% block content %}

<!-- STATISTIC-->
<section class="statistic">
    <div class="section__content section__content--p30">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-6 col-lg-3">
                    <div class="statistic__item">
                        <h2 class="number">{% asset_count %}</h2>
                        <span class="desc"><a href="{% url 'assets:asset-list' %}">{% trans 'Actifs' %}</a></span>
                        <div class="icon">
                            <i class="zmdi zmdi-collection-item"></i>
                        </div>
                    </div>
                </div>
                <div class="col-md-6 col-lg-3">
                    <div class="statistic__item">
                        <h2 class="number">{% location_count %}</h2>
                        <span class="desc"><a href="{% url 'assets:location-list' %}">{% trans 'Emplacements' %}</a></span>
                        <div class="icon">
                            <i class="zmdi zmdi-globe"></i>
                        </div>
                    </div>
                </div>
                <div class="col-md-6 col-lg-3">
                    <div class="statistic__item">
                        <h2 class="number">{% supplier_count %}</h2>
                        <span class="desc"><a href="{% url 'assets:supplier-list' %}">{% trans 'Fournisseurs' %}</a></span>
                        <div class="icon">
                            <i class="zmdi zmdi-truck"></i>
                        </div>
                    </div>
                </div>
                <div class="col-md-6 col-lg-3">
                  <div class="statistic__item">
                    <h2 class="number">${% assets_value %}</h2>
                    <span class="desc">{% trans 'Valeur totale' %}</span>
                    <div class="icon">
                      <i class="zmdi zmdi-money"></i>
                    </div>
                  </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- END STATISTIC-->

<section>
    <div class="section__content section__content--p30">
        <div class="container-fluid">
            <div class="row">
              <div class="col-xl-8">
                  <!-- USER DATA-->
                  <div class="user-data m-b-40">
                      <h3 class="title-3 m-b-30">
                          <i class="zmdi zmdi-account-calendar"></i>
                          Utilisateurs
                      </h3>
                      <div class="table-responsive table-data">
                          <table class="table">
                              <thead>
                                  <tr>
                                      <td>
                                          <label class="au-checkbox">
                                              <input type="checkbox">
                                              <span class="au-checkmark"></span>
                                          </label>
                                      </td>
                                      <td>Nom</td>
                                      <td>Groupes</td>
                                      <td>Nom d'utilisateur</td>
                                      <td></td>
                                  </tr>
                              </thead>
                              <tbody>
                                {% for user in users %}
                                  <tr>
                                      <td>
                                          <label class="au-checkbox">
                                              <input type="checkbox">
                                              <span class="au-checkmark"></span>
                                          </label>
                                      </td>
                                      <td>
                                          <div class="table-data__info">
                                              <h6>{{ user.username }}</h6>
                                              <span>
                                                  <a href="#">{{ user.email }}</a>
                                              </span>
                                          </div>
                                      </td>
                                      <td>
                                          {{ user.username }}
                                      </td>
                                      <td>
                                        {% for group in users.groups %}
                                          <span class="role admin">{{ group }}</span>
                                        {% endfor %}
                                        {% if user.is_superuser %}
                                          <span class="role admin">Administrateur</span>
                                        {% endif %}
                                      </td>
                                      <td>
                                          <span class="more">
                                              <i class="zmdi zmdi-more"></i>
                                          </span>
                                      </td>
                                  </tr>
                                {% endfor %}

                              </tbody>
                          </table>
                      </div>
                  </div>
                  <!-- END USER DATA-->
              </div>
                <div class="col-xl-4">
                    <!-- TASK PROGRESS-->
                    <div class="task-progress">
                        <h3 class="title-3">{% trans 'État des actifs'%}</h3>
                        <div class="au-skill-container">
                            <canvas id="assets_states_chart"></canvas>
                        </div>
                    </div>
                    <!-- END TASK PROGRESS-->
                </div>
            </div>
        </div>
    </div>
</section>

<section>
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="copyright">
                    <p>Copyright © 2018 Colorlib. All rights reserved. Template by <a href="https://colorlib.com">Colorlib</a>.</p>
                </div>
            </div>
        </div>
    </div>
</section>


{% endblock %}

{% block extra_footer_scripts %}
<script>
var colors = [

  '#232346', // pink
  '#3280FF', // blue
  '#6400FF', // red
  '#480C9F', // green
  '#00FFFF', // orange
  '#4D4D4D', // gray
  '#5DA5DA', // blue
  '#FAA43A', // orange
  '#F15854', // red
  '#60BD68', // green
  '#F17CB0', // pink
  '#4D4D4D', // gray
  '#5DA5DA', // blue
  '#FAA43A', // orange
  '#F15854', // red
  '#60BD68', // green
  '#F17CB0', // pink
  '#4D4D4D', // gray
  '#5DA5DA', // blue
  '#FAA43A', // orange
  '#F15854', // red
  '#60BD68', // green
  '#F17CB0', // pink
  '#4D4D4D', // gray
]
var state_data = []
var state_labels = []

{% assets_states as states %}
{% for state, count in states.items %}
state_data.push({{ count }});
state_labels.push("{{ state|escapejs }}");
{% endfor %}

var data = {
  datasets: [{
    data: state_data,
    backgroundColor: colors,
  }],
  labels: state_labels,
}
var options = {
    legend:{
        display: true,
        position: 'right',
        labels:{
            fontColor: '#000',
        }
    }
}

var ctx = document.getElementById("assets_states_chart");

var myPieChart = new Chart(ctx,{
    type: 'doughnut',
    data: data,
    options: options
});

</script>
{% endblock %}